services:
  hugo-nsde:
    build: ./src/.
    hostname: hugo-nsde
    container_name: hugo-nsde
    restart: unless-stopped
    volumes:
      - ./content:/hugo/content
      - ./theme:/hugo/themes/theme
      - ./dist:/hugo/dist
      - ./hugo.toml:/hugo/hugo.toml
    env_file: .env
    ports:
      - "1313:1313"