name = 'niklas-stephan.de 2025'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Theme for my personal website at niklas-stephan.de'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://niklas-stephan.de'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has multiple authors
authors = [
  {name = 'Niklas Stephan', homepage = 'https://niklas-stephan.de'}
]


